#公共配置
server:
  port: 7091

spring:
  application:
    name: wechatmall
  messages:
    basename: i18n/Messages,i18n/Pages

  resources:
    static-locations: classpath:/statics/
  datasource:
    name: ddglxt
#url: jdbc:mysql://localhost:3306/ddglxt?useUnicode=true&amp;characterEncoding=UTF-8
    url: jdbc:mysql://127.0.0.1:3306/ddglxt?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: ddglxt
    password: ddglxt
#使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  redis:
    host: localhost
    port: 6379
#password:
    database: 0
    timeout: 200


    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # 连接池中的最大空闲连接
      max-idle: 8
    # 连接池中的最小空闲连接
      min-idle: 0

