#公共配置
server:
  port: 12016

spring:
# 配置路由设置
#  profiles:
#    active: test
  messages:
    basename: i18n/Messages,i18n/Pages
#接口地址
config:
  systemcontant:
    url: http://localhost:7001/services/WsService?wsdl