#公共配置
server:
  port: 7012

spring:
  application:
    name: dubbo-consumer
  messages:
    basename: i18n/Messages,i18n/Pages


# DemoService service version
demo:
  service:
    version: 1.0.0


dubbo:
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
    qos:
      port: 22223
      enable: true
  # Base packages to scan Dubbo Component: @com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: cn.dyaoming.outman.dubbo.services.impl
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12346
    status: server

  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: zookeeper://127.0.0.1:2181

# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true

    # Dubbo Health
    ## StatusChecker Name defaults (default : "memory", "load" )
  health:
    dubbo:
      status:
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool