#公共配置
server:
  port: 7011

spring:
#  profiles:
#    active: test
  messages:
    basename: i18n/Messages,i18n/Pages
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
