#公共配置
server:
  port: 7091

spring:
  application:
    name: wechatmall
  messages:
    basename: i18n/Messages,i18n/Pages

  datasource:
    name: ddglxt
    url: jdbc:mysql://localhost:3306/ddglxt?useUnicode=true&amp;characterEncoding=UTF-8
    username: ddglxt
    password: ddglxt
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20