#公共配置
server:
  port: 7013

spring:
#  profiles:
#    active: zhkj
  messages:
    basename: i18n/Messages,i18n/Pages
  jms:
    pub-sub-domain: false   # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
  activemq:
    user: admin    # 连接用户名
    password: admin   # 连接密码
    broker-url: tcp://localhost:61616 # 消息组件的连接主机信息

